#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [[ $# -ne 2 ]];
then echo "Wrong usage"
     exit 1
fi

source $DIR/../venv/bin/activate
python $DIR/../bindings/python/delete.py "removerule" "$1" "$2"
deactivate
