#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"

if [[ $# -ne 6 ]];
then echo "Wrong usage"
     exit 1
fi

source $DIR/../venv/bin/activate
python $DIR/../bindings/python/commands.py "updatefact" "$1" "$2" "$3" "$4" "$5" "$6"
deactivate
