# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioPacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='AudioPacket.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x11\x41udioPacket.proto\"o\n\x0f\x41udioDataPacket\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x12\n\nsampleRate\x18\x02 \x01(\x05\x12\x10\n\x08\x63hannels\x18\x03 \x01(\x05\x12\x15\n\rbitsPerSample\x18\x04 \x01(\x05\x12\x0c\n\x04\x64\x61ta\x18\x05 \x01(\x0c\x42\x15\xaa\x02\x12SmartApp.HAL.Modelb\x06proto3')
)




_AUDIODATAPACKET = _descriptor.Descriptor(
  name='AudioDataPacket',
  full_name='AudioDataPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='AudioDataPacket.timestamp', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sampleRate', full_name='AudioDataPacket.sampleRate', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='channels', full_name='AudioDataPacket.channels', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='bitsPerSample', full_name='AudioDataPacket.bitsPerSample', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='AudioDataPacket.data', index=4,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=132,
)

DESCRIPTOR.message_types_by_name['AudioDataPacket'] = _AUDIODATAPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AudioDataPacket = _reflection.GeneratedProtocolMessageType('AudioDataPacket', (_message.Message,), dict(
  DESCRIPTOR = _AUDIODATAPACKET,
  __module__ = 'AudioPacket_pb2'
  # @@protoc_insertion_point(class_scope:AudioDataPacket)
  ))
_sym_db.RegisterMessage(AudioDataPacket)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\252\002\022SmartApp.HAL.Model'))
# @@protoc_insertion_point(module_scope)
