# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VideoPacket.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='VideoPacket.proto',
  package='',
  syntax='proto3',
  serialized_options=_b('\252\002\022SmartApp.HAL.Model'),
  serialized_pb=_b('\n\x11VideoPacket.proto\"\x8e\x01\n\x12VideoControlPacket\x12\x43\n\x10\x66ramerateRequest\x18\x01 \x01(\x0b\x32\'.VideoControlPacket.SetFramerateRequestH\x00\x1a(\n\x13SetFramerateRequest\x12\x11\n\tframerate\x18\x01 \x01(\rB\t\n\x07Request\"l\n\x0fVideoDataPacket\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12$\n\x05\x66\x61\x63\x65s\x18\x02 \x03(\x0b\x32\x15.VideoDataPacket.Face\x1a \n\x04\x46\x61\x63\x65\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\x0c\x42\x15\xaa\x02\x12SmartApp.HAL.Modelb\x06proto3')
)




_VIDEOCONTROLPACKET_SETFRAMERATEREQUEST = _descriptor.Descriptor(
  name='SetFramerateRequest',
  full_name='VideoControlPacket.SetFramerateRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='framerate', full_name='VideoControlPacket.SetFramerateRequest.framerate', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=153,
)

_VIDEOCONTROLPACKET = _descriptor.Descriptor(
  name='VideoControlPacket',
  full_name='VideoControlPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='framerateRequest', full_name='VideoControlPacket.framerateRequest', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VIDEOCONTROLPACKET_SETFRAMERATEREQUEST, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='Request', full_name='VideoControlPacket.Request',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=22,
  serialized_end=164,
)


_VIDEODATAPACKET_FACE = _descriptor.Descriptor(
  name='Face',
  full_name='VideoDataPacket.Face',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='VideoDataPacket.Face.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='data', full_name='VideoDataPacket.Face.data', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=274,
)

_VIDEODATAPACKET = _descriptor.Descriptor(
  name='VideoDataPacket',
  full_name='VideoDataPacket',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='VideoDataPacket.timestamp', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='faces', full_name='VideoDataPacket.faces', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_VIDEODATAPACKET_FACE, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=166,
  serialized_end=274,
)

_VIDEOCONTROLPACKET_SETFRAMERATEREQUEST.containing_type = _VIDEOCONTROLPACKET
_VIDEOCONTROLPACKET.fields_by_name['framerateRequest'].message_type = _VIDEOCONTROLPACKET_SETFRAMERATEREQUEST
_VIDEOCONTROLPACKET.oneofs_by_name['Request'].fields.append(
  _VIDEOCONTROLPACKET.fields_by_name['framerateRequest'])
_VIDEOCONTROLPACKET.fields_by_name['framerateRequest'].containing_oneof = _VIDEOCONTROLPACKET.oneofs_by_name['Request']
_VIDEODATAPACKET_FACE.containing_type = _VIDEODATAPACKET
_VIDEODATAPACKET.fields_by_name['faces'].message_type = _VIDEODATAPACKET_FACE
DESCRIPTOR.message_types_by_name['VideoControlPacket'] = _VIDEOCONTROLPACKET
DESCRIPTOR.message_types_by_name['VideoDataPacket'] = _VIDEODATAPACKET
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

VideoControlPacket = _reflection.GeneratedProtocolMessageType('VideoControlPacket', (_message.Message,), dict(

  SetFramerateRequest = _reflection.GeneratedProtocolMessageType('SetFramerateRequest', (_message.Message,), dict(
    DESCRIPTOR = _VIDEOCONTROLPACKET_SETFRAMERATEREQUEST,
    __module__ = 'VideoPacket_pb2'
    # @@protoc_insertion_point(class_scope:VideoControlPacket.SetFramerateRequest)
    ))
  ,
  DESCRIPTOR = _VIDEOCONTROLPACKET,
  __module__ = 'VideoPacket_pb2'
  # @@protoc_insertion_point(class_scope:VideoControlPacket)
  ))
_sym_db.RegisterMessage(VideoControlPacket)
_sym_db.RegisterMessage(VideoControlPacket.SetFramerateRequest)

VideoDataPacket = _reflection.GeneratedProtocolMessageType('VideoDataPacket', (_message.Message,), dict(

  Face = _reflection.GeneratedProtocolMessageType('Face', (_message.Message,), dict(
    DESCRIPTOR = _VIDEODATAPACKET_FACE,
    __module__ = 'VideoPacket_pb2'
    # @@protoc_insertion_point(class_scope:VideoDataPacket.Face)
    ))
  ,
  DESCRIPTOR = _VIDEODATAPACKET,
  __module__ = 'VideoPacket_pb2'
  # @@protoc_insertion_point(class_scope:VideoDataPacket)
  ))
_sym_db.RegisterMessage(VideoDataPacket)
_sym_db.RegisterMessage(VideoDataPacket.Face)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
