//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ConnectionReader : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ConnectionReader(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ConnectionReader obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ConnectionReader() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ConnectionReader(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool expectBlock(string data, uint len) {
    bool ret = yarpPINVOKE.ConnectionReader_expectBlock(swigCPtr, data, len);
    return ret;
  }

  public virtual string expectText(int terminatingChar) {
    string ret = yarpPINVOKE.ConnectionReader_expectText__SWIG_0(swigCPtr, terminatingChar);
    return ret;
  }

  public virtual string expectText() {
    string ret = yarpPINVOKE.ConnectionReader_expectText__SWIG_1(swigCPtr);
    return ret;
  }

  public virtual int expectInt() {
    int ret = yarpPINVOKE.ConnectionReader_expectInt(swigCPtr);
    return ret;
  }

  public virtual sbyte expectInt8() {
    sbyte ret = yarpPINVOKE.ConnectionReader_expectInt8(swigCPtr);
    return ret;
  }

  public virtual short expectInt16() {
    short ret = yarpPINVOKE.ConnectionReader_expectInt16(swigCPtr);
    return ret;
  }

  public virtual int expectInt32() {
    int ret = yarpPINVOKE.ConnectionReader_expectInt32(swigCPtr);
    return ret;
  }

  public virtual long expectInt64() {
    long ret = yarpPINVOKE.ConnectionReader_expectInt64(swigCPtr);
    return ret;
  }

  public virtual double expectDouble() {
    double ret = yarpPINVOKE.ConnectionReader_expectDouble(swigCPtr);
    return ret;
  }

  public virtual float expectFloat32() {
    float ret = yarpPINVOKE.ConnectionReader_expectFloat32(swigCPtr);
    return ret;
  }

  public virtual double expectFloat64() {
    double ret = yarpPINVOKE.ConnectionReader_expectFloat64(swigCPtr);
    return ret;
  }

  public virtual bool isTextMode() {
    bool ret = yarpPINVOKE.ConnectionReader_isTextMode(swigCPtr);
    return ret;
  }

  public virtual bool isBareMode() {
    bool ret = yarpPINVOKE.ConnectionReader_isBareMode(swigCPtr);
    return ret;
  }

  public virtual bool convertTextMode() {
    bool ret = yarpPINVOKE.ConnectionReader_convertTextMode(swigCPtr);
    return ret;
  }

  public virtual uint getSize() {
    uint ret = yarpPINVOKE.ConnectionReader_getSize(swigCPtr);
    return ret;
  }

  public virtual ConnectionWriter getWriter() {
    global::System.IntPtr cPtr = yarpPINVOKE.ConnectionReader_getWriter(swigCPtr);
    ConnectionWriter ret = (cPtr == global::System.IntPtr.Zero) ? null : new ConnectionWriter(cPtr, false);
    return ret;
  }

  public virtual SWIGTYPE_p_Bytes readEnvelope() {
    SWIGTYPE_p_Bytes ret = new SWIGTYPE_p_Bytes(yarpPINVOKE.ConnectionReader_readEnvelope(swigCPtr), true);
    return ret;
  }

  public virtual Portable getReference() {
    global::System.IntPtr cPtr = yarpPINVOKE.ConnectionReader_getReference(swigCPtr);
    Portable ret = (cPtr == global::System.IntPtr.Zero) ? null : new Portable(cPtr, false);
    return ret;
  }

  public virtual Contact getRemoteContact() {
    Contact ret = new Contact(yarpPINVOKE.ConnectionReader_getRemoteContact(swigCPtr), true);
    return ret;
  }

  public virtual Contact getLocalContact() {
    Contact ret = new Contact(yarpPINVOKE.ConnectionReader_getLocalContact(swigCPtr), true);
    return ret;
  }

  public virtual bool isValid() {
    bool ret = yarpPINVOKE.ConnectionReader_isValid(swigCPtr);
    return ret;
  }

  public virtual bool isActive() {
    bool ret = yarpPINVOKE.ConnectionReader_isActive(swigCPtr);
    return ret;
  }

  public virtual bool isError() {
    bool ret = yarpPINVOKE.ConnectionReader_isError(swigCPtr);
    return ret;
  }

  public virtual void requestDrop() {
    yarpPINVOKE.ConnectionReader_requestDrop(swigCPtr);
  }

  public virtual Searchable getConnectionModifiers() {
    Searchable ret = new Searchable(yarpPINVOKE.ConnectionReader_getConnectionModifiers(swigCPtr), false);
    return ret;
  }

  public virtual bool pushInt(int x) {
    bool ret = yarpPINVOKE.ConnectionReader_pushInt(swigCPtr, x);
    return ret;
  }

  public virtual bool setSize(uint len) {
    bool ret = yarpPINVOKE.ConnectionReader_setSize(swigCPtr, len);
    return ret;
  }

  public static ConnectionReader createConnectionReader(SWIGTYPE_p_yarp__os__InputStream arg0) {
    global::System.IntPtr cPtr = yarpPINVOKE.ConnectionReader_createConnectionReader(SWIGTYPE_p_yarp__os__InputStream.getCPtr(arg0));
    ConnectionReader ret = (cPtr == global::System.IntPtr.Zero) ? null : new ConnectionReader(cPtr, false);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool readFromStream(PortReader portable, SWIGTYPE_p_yarp__os__InputStream arg1) {
    bool ret = yarpPINVOKE.ConnectionReader_readFromStream(PortReader.getCPtr(portable), SWIGTYPE_p_yarp__os__InputStream.getCPtr(arg1));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void setParentConnectionReader(ConnectionReader parentConnectionReader) {
    yarpPINVOKE.ConnectionReader_setParentConnectionReader(swigCPtr, ConnectionReader.getCPtr(parentConnectionReader));
  }

}
