//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Contact : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal Contact(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Contact obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Contact() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_Contact(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Contact(string name, string carrier, string hostname, int port) : this(yarpPINVOKE.new_Contact__SWIG_0(name, carrier, hostname, port), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Contact(string name, string carrier, string hostname) : this(yarpPINVOKE.new_Contact__SWIG_1(name, carrier, hostname), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Contact(string name, string carrier) : this(yarpPINVOKE.new_Contact__SWIG_2(name, carrier), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Contact(string name) : this(yarpPINVOKE.new_Contact__SWIG_3(name), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Contact() : this(yarpPINVOKE.new_Contact__SWIG_4(), true) {
  }

  public Contact(string hostname, int port) : this(yarpPINVOKE.new_Contact__SWIG_5(hostname, port), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Contact(string carrier, string hostname, int port) : this(yarpPINVOKE.new_Contact__SWIG_6(carrier, hostname, port), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public Contact(Contact rhs) : this(yarpPINVOKE.new_Contact__SWIG_7(Contact.getCPtr(rhs)), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static Contact fromConfig(Searchable config) {
    Contact ret = new Contact(yarpPINVOKE.Contact_fromConfig(Searchable.getCPtr(config)), true);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static Contact fromString(string txt) {
    Contact ret = new Contact(yarpPINVOKE.Contact_fromString(txt), true);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string getName() {
    string ret = yarpPINVOKE.Contact_getName(swigCPtr);
    return ret;
  }

  public void setName(string name) {
    yarpPINVOKE.Contact_setName(swigCPtr, name);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public string getRegName() {
    string ret = yarpPINVOKE.Contact_getRegName(swigCPtr);
    return ret;
  }

  public string getHost() {
    string ret = yarpPINVOKE.Contact_getHost(swigCPtr);
    return ret;
  }

  public void setHost(string hostname) {
    yarpPINVOKE.Contact_setHost(swigCPtr, hostname);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public int getPort() {
    int ret = yarpPINVOKE.Contact_getPort(swigCPtr);
    return ret;
  }

  public void setPort(int port) {
    yarpPINVOKE.Contact_setPort(swigCPtr, port);
  }

  public string getCarrier() {
    string ret = yarpPINVOKE.Contact_getCarrier(swigCPtr);
    return ret;
  }

  public void setCarrier(string carrier) {
    yarpPINVOKE.Contact_setCarrier(swigCPtr, carrier);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public SWIGTYPE_p_NestedContact getNested() {
    SWIGTYPE_p_NestedContact ret = new SWIGTYPE_p_NestedContact(yarpPINVOKE.Contact_getNested(swigCPtr), false);
    return ret;
  }

  public void setNestedContact(SWIGTYPE_p_yarp__os__NestedContact nestedContact) {
    yarpPINVOKE.Contact_setNestedContact(swigCPtr, SWIGTYPE_p_yarp__os__NestedContact.getCPtr(nestedContact));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool hasTimeout() {
    bool ret = yarpPINVOKE.Contact_hasTimeout(swigCPtr);
    return ret;
  }

  public float getTimeout() {
    float ret = yarpPINVOKE.Contact_getTimeout(swigCPtr);
    return ret;
  }

  public void setTimeout(float timeout) {
    yarpPINVOKE.Contact_setTimeout(swigCPtr, timeout);
  }

  public void setSocket(string carrier, string hostname, int port) {
    yarpPINVOKE.Contact_setSocket(swigCPtr, carrier, hostname, port);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool isValid() {
    bool ret = yarpPINVOKE.Contact_isValid(swigCPtr);
    return ret;
  }

  public new string toString_c() {
    string ret = yarpPINVOKE.Contact_toString_c(swigCPtr);
    return ret;
  }

  public string toURI(bool includeCarrier) {
    string ret = yarpPINVOKE.Contact_toURI__SWIG_0(swigCPtr, includeCarrier);
    return ret;
  }

  public string toURI() {
    string ret = yarpPINVOKE.Contact_toURI__SWIG_1(swigCPtr);
    return ret;
  }

  public static string convertHostToIp(string name) {
    string ret = yarpPINVOKE.Contact_convertHostToIp(name);
    return ret;
  }

}
