//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class GazeEvent : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal GazeEvent(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(GazeEvent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~GazeEvent() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_GazeEvent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public GazeEventParameters gazeEventParameters {
    set {
      yarpPINVOKE.GazeEvent_gazeEventParameters_set(swigCPtr, GazeEventParameters.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = yarpPINVOKE.GazeEvent_gazeEventParameters_get(swigCPtr);
      GazeEventParameters ret = (cPtr == global::System.IntPtr.Zero) ? null : new GazeEventParameters(cPtr, false);
      return ret;
    } 
  }

  public GazeEventVariables gazeEventVariables {
    set {
      yarpPINVOKE.GazeEvent_gazeEventVariables_set(swigCPtr, GazeEventVariables.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = yarpPINVOKE.GazeEvent_gazeEventVariables_get(swigCPtr);
      GazeEventVariables ret = (cPtr == global::System.IntPtr.Zero) ? null : new GazeEventVariables(cPtr, false);
      return ret;
    } 
  }

  public virtual void gazeEventCallback() {
    yarpPINVOKE.GazeEvent_gazeEventCallback(swigCPtr);
  }

}
