//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IControlDebug : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IControlDebug(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IControlDebug obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IControlDebug() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IControlDebug(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool setPrintFunction(SWIGTYPE_p_f_p_q_const__char_v_______int f) {
    bool ret = yarpPINVOKE.IControlDebug_setPrintFunction(swigCPtr, SWIGTYPE_p_f_p_q_const__char_v_______int.getCPtr(f));
    return ret;
  }

  public virtual bool loadBootMemory() {
    bool ret = yarpPINVOKE.IControlDebug_loadBootMemory(swigCPtr);
    return ret;
  }

  public virtual bool saveBootMemory() {
    bool ret = yarpPINVOKE.IControlDebug_saveBootMemory(swigCPtr);
    return ret;
  }

}
