//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IEncoderArrays : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IEncoderArrays(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IEncoderArrays obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IEncoderArrays() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IEncoderArrays(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual uint getNrOfEncoderArrays() {
    uint ret = yarpPINVOKE.IEncoderArrays_getNrOfEncoderArrays(swigCPtr);
    return ret;
  }

  public virtual MAS_status getEncoderArrayStatus(uint sens_index) {
    MAS_status ret = (MAS_status)yarpPINVOKE.IEncoderArrays_getEncoderArrayStatus(swigCPtr, sens_index);
    return ret;
  }

  public virtual bool getEncoderArrayName(uint sens_index, SWIGTYPE_p_std__string name) {
    bool ret = yarpPINVOKE.IEncoderArrays_getEncoderArrayName(swigCPtr, sens_index, SWIGTYPE_p_std__string.getCPtr(name));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool getEncoderArrayMeasure(uint sens_index, Vector arg1, SWIGTYPE_p_double timestamp) {
    bool ret = yarpPINVOKE.IEncoderArrays_getEncoderArrayMeasure(swigCPtr, sens_index, Vector.getCPtr(arg1), SWIGTYPE_p_double.getCPtr(timestamp));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual uint getEncoderArraySize(uint sens_index) {
    uint ret = yarpPINVOKE.IEncoderArrays_getEncoderArraySize(swigCPtr, sens_index);
    return ret;
  }

}
