//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IInteractionMode : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IInteractionMode(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IInteractionMode obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IInteractionMode() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IInteractionMode(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool getInteractionMode(int axis, SWIGTYPE_p_yarp__dev__InteractionModeEnum mode) {
    bool ret = yarpPINVOKE.IInteractionMode_getInteractionMode__SWIG_0(swigCPtr, axis, SWIGTYPE_p_yarp__dev__InteractionModeEnum.getCPtr(mode));
    return ret;
  }

  public virtual bool getInteractionModes(int n_joints, SWIGTYPE_p_int joints, SWIGTYPE_p_yarp__dev__InteractionModeEnum modes) {
    bool ret = yarpPINVOKE.IInteractionMode_getInteractionModes__SWIG_0(swigCPtr, n_joints, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_yarp__dev__InteractionModeEnum.getCPtr(modes));
    return ret;
  }

  public virtual bool getInteractionModes(SWIGTYPE_p_yarp__dev__InteractionModeEnum modes) {
    bool ret = yarpPINVOKE.IInteractionMode_getInteractionModes__SWIG_1(swigCPtr, SWIGTYPE_p_yarp__dev__InteractionModeEnum.getCPtr(modes));
    return ret;
  }

  public virtual bool setInteractionMode(int axis, InteractionModeEnum mode) {
    bool ret = yarpPINVOKE.IInteractionMode_setInteractionMode(swigCPtr, axis, (int)mode);
    return ret;
  }

  public virtual bool setInteractionModes(int n_joints, SWIGTYPE_p_int joints, SWIGTYPE_p_yarp__dev__InteractionModeEnum modes) {
    bool ret = yarpPINVOKE.IInteractionMode_setInteractionModes__SWIG_0(swigCPtr, n_joints, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_yarp__dev__InteractionModeEnum.getCPtr(modes));
    return ret;
  }

  public virtual bool setInteractionModes(SWIGTYPE_p_yarp__dev__InteractionModeEnum modes) {
    bool ret = yarpPINVOKE.IInteractionMode_setInteractionModes__SWIG_1(swigCPtr, SWIGTYPE_p_yarp__dev__InteractionModeEnum.getCPtr(modes));
    return ret;
  }

  public InteractionModeEnum getInteractionMode(int axis) {
    InteractionModeEnum ret = (InteractionModeEnum)yarpPINVOKE.IInteractionMode_getInteractionMode__SWIG_1(swigCPtr, axis);
    return ret;
  }

}
