//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ImageMono : Image {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ImageMono(global::System.IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.ImageMono_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageMono obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageMono() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ImageMono(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ImageMono() : this(yarpPINVOKE.new_ImageMono(), true) {
  }

  public override uint getPixelSize() {
    uint ret = yarpPINVOKE.ImageMono_getPixelSize(swigCPtr);
    return ret;
  }

  public override int getPixelCode() {
    int ret = yarpPINVOKE.ImageMono_getPixelCode(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char pixel(uint x, uint y) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(yarpPINVOKE.ImageMono_pixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public byte access(uint x, uint y) {
    byte ret = yarpPINVOKE.ImageMono_access__SWIG_0(swigCPtr, x, y);
    return ret;
  }

  public SWIGTYPE_p_unsigned_char safePixel(uint x, uint y) {
    SWIGTYPE_p_unsigned_char ret = new SWIGTYPE_p_unsigned_char(yarpPINVOKE.ImageMono_safePixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

}
