//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class Image : Portable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal Image(global::System.IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.Image_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(Image obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~Image() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_Image(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public Image() : this(yarpPINVOKE.new_Image__SWIG_0(), true) {
  }

  public Image(Image alt) : this(yarpPINVOKE.new_Image__SWIG_1(Image.getCPtr(alt)), true) {
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool copy(Image alt) {
    bool ret = yarpPINVOKE.Image_copy__SWIG_0(swigCPtr, Image.getCPtr(alt));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool copy(Image alt, uint w, uint h) {
    bool ret = yarpPINVOKE.Image_copy__SWIG_1(swigCPtr, Image.getCPtr(alt), w, h);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public uint width() {
    uint ret = yarpPINVOKE.Image_width(swigCPtr);
    return ret;
  }

  public uint height() {
    uint ret = yarpPINVOKE.Image_height(swigCPtr);
    return ret;
  }

  public virtual uint getPixelSize() {
    uint ret = yarpPINVOKE.Image_getPixelSize(swigCPtr);
    return ret;
  }

  public virtual int getPixelCode() {
    int ret = yarpPINVOKE.Image_getPixelCode(swigCPtr);
    return ret;
  }

  public uint getRowSize() {
    uint ret = yarpPINVOKE.Image_getRowSize(swigCPtr);
    return ret;
  }

  public uint getQuantum() {
    uint ret = yarpPINVOKE.Image_getQuantum(swigCPtr);
    return ret;
  }

  public uint getPadding() {
    uint ret = yarpPINVOKE.Image_getPadding(swigCPtr);
    return ret;
  }

  public System.IntPtr getRow(uint r) { return yarpPINVOKE.Image_getRow__SWIG_0(swigCPtr, r); }

  public System.IntPtr getPixelAddress(uint x, uint y) { return yarpPINVOKE.Image_getPixelAddress(swigCPtr, x, y); }

  public bool isPixel(uint x, uint y) {
    bool ret = yarpPINVOKE.Image_isPixel(swigCPtr, x, y);
    return ret;
  }

  public void zero() {
    yarpPINVOKE.Image_zero(swigCPtr);
  }

  public void resize(uint imgWidth, uint imgHeight) {
    yarpPINVOKE.Image_resize__SWIG_0(swigCPtr, imgWidth, imgHeight);
  }

  public void resize(Image alt) {
    yarpPINVOKE.Image_resize__SWIG_1(swigCPtr, Image.getCPtr(alt));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public void setExternal(SWIGTYPE_p_void data, uint imgWidth, uint imgHeight) {
    yarpPINVOKE.Image_setExternal(swigCPtr, SWIGTYPE_p_void.getCPtr(data), imgWidth, imgHeight);
  }

  public System.IntPtr getRawImage() { return yarpPINVOKE.Image_getRawImage(swigCPtr); }

  public uint getRawImageSize() {
    uint ret = yarpPINVOKE.Image_getRawImageSize(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_void getIplImage() {
    global::System.IntPtr cPtr = yarpPINVOKE.Image_getIplImage(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public void wrapIplImage(SWIGTYPE_p_void iplImage) {
    yarpPINVOKE.Image_wrapIplImage(swigCPtr, SWIGTYPE_p_void.getCPtr(iplImage));
  }

  public new bool read(ConnectionReader connection) {
    bool ret = yarpPINVOKE.Image_read(swigCPtr, ConnectionReader.getCPtr(connection));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new bool write(ConnectionWriter connection) {
    bool ret = yarpPINVOKE.Image_write(swigCPtr, ConnectionWriter.getCPtr(connection));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void setQuantum(uint imgQuantum) {
    yarpPINVOKE.Image_setQuantum(swigCPtr, imgQuantum);
  }

  public bool topIsLowIndex() {
    bool ret = yarpPINVOKE.Image_topIsLowIndex(swigCPtr);
    return ret;
  }

  public void setTopIsLowIndex(bool flag) {
    yarpPINVOKE.Image_setTopIsLowIndex(swigCPtr, flag);
  }

  public SWIGTYPE_p_p_char getRowArray() {
    global::System.IntPtr cPtr = yarpPINVOKE.Image_getRowArray(swigCPtr);
    SWIGTYPE_p_p_char ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_p_char(cPtr, false);
    return ret;
  }

}
