//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ImageRgbFloat : Image {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ImageRgbFloat(global::System.IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.ImageRgbFloat_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageRgbFloat obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageRgbFloat() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ImageRgbFloat(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ImageRgbFloat() : this(yarpPINVOKE.new_ImageRgbFloat(), true) {
  }

  public override uint getPixelSize() {
    uint ret = yarpPINVOKE.ImageRgbFloat_getPixelSize(swigCPtr);
    return ret;
  }

  public override int getPixelCode() {
    int ret = yarpPINVOKE.ImageRgbFloat_getPixelCode(swigCPtr);
    return ret;
  }

  public PixelRgbFloat pixel(uint x, uint y) {
    PixelRgbFloat ret = new PixelRgbFloat(yarpPINVOKE.ImageRgbFloat_pixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public PixelRgbFloat access(uint x, uint y) {
    PixelRgbFloat ret = new PixelRgbFloat(yarpPINVOKE.ImageRgbFloat_access__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public PixelRgbFloat safePixel(uint x, uint y) {
    PixelRgbFloat ret = new PixelRgbFloat(yarpPINVOKE.ImageRgbFloat_safePixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

}
