//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class ImageMono16 : Image {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ImageMono16(global::System.IntPtr cPtr, bool cMemoryOwn) : base(yarpPINVOKE.ImageMono16_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ImageMono16 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ImageMono16() {
    Dispose();
  }

  public override void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_ImageMono16(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
      base.Dispose();
    }
  }

  public ImageMono16() : this(yarpPINVOKE.new_ImageMono16(), true) {
  }

  public override uint getPixelSize() {
    uint ret = yarpPINVOKE.ImageMono16_getPixelSize(swigCPtr);
    return ret;
  }

  public override int getPixelCode() {
    int ret = yarpPINVOKE.ImageMono16_getPixelCode(swigCPtr);
    return ret;
  }

  public SWIGTYPE_p_yarp__os__NetUint16 pixel(uint x, uint y) {
    SWIGTYPE_p_yarp__os__NetUint16 ret = new SWIGTYPE_p_yarp__os__NetUint16(yarpPINVOKE.ImageMono16_pixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public SWIGTYPE_p_yarp__os__NetUint16 access(uint x, uint y) {
    SWIGTYPE_p_yarp__os__NetUint16 ret = new SWIGTYPE_p_yarp__os__NetUint16(yarpPINVOKE.ImageMono16_access__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

  public SWIGTYPE_p_yarp__os__NetUint16 safePixel(uint x, uint y) {
    SWIGTYPE_p_yarp__os__NetUint16 ret = new SWIGTYPE_p_yarp__os__NetUint16(yarpPINVOKE.ImageMono16_safePixel__SWIG_0(swigCPtr, x, y), false);
    return ret;
  }

}
