//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IPositionControl : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IPositionControl(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IPositionControl obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IPositionControl() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IPositionControl(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual bool getAxes(SWIGTYPE_p_int ax) {
    bool ret = yarpPINVOKE.IPositionControl_getAxes__SWIG_0(swigCPtr, SWIGTYPE_p_int.getCPtr(ax));
    return ret;
  }

  public virtual bool positionMove(int j, double arg1) {
    bool ret = yarpPINVOKE.IPositionControl_positionMove__SWIG_0(swigCPtr, j, arg1);
    return ret;
  }

  public virtual bool positionMove(SWIGTYPE_p_double refs) {
    bool ret = yarpPINVOKE.IPositionControl_positionMove__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(refs));
    return ret;
  }

  public virtual bool relativeMove(int j, double delta) {
    bool ret = yarpPINVOKE.IPositionControl_relativeMove__SWIG_0(swigCPtr, j, delta);
    return ret;
  }

  public virtual bool relativeMove(SWIGTYPE_p_double deltas) {
    bool ret = yarpPINVOKE.IPositionControl_relativeMove__SWIG_1(swigCPtr, SWIGTYPE_p_double.getCPtr(deltas));
    return ret;
  }

  public virtual bool checkMotionDone(int j, SWIGTYPE_p_bool flag) {
    bool ret = yarpPINVOKE.IPositionControl_checkMotionDone__SWIG_0(swigCPtr, j, SWIGTYPE_p_bool.getCPtr(flag));
    return ret;
  }

  public virtual bool checkMotionDone(SWIGTYPE_p_bool flag) {
    bool ret = yarpPINVOKE.IPositionControl_checkMotionDone__SWIG_1(swigCPtr, SWIGTYPE_p_bool.getCPtr(flag));
    return ret;
  }

  public virtual bool setRefSpeed(int j, double sp) {
    bool ret = yarpPINVOKE.IPositionControl_setRefSpeed(swigCPtr, j, sp);
    return ret;
  }

  public virtual bool setRefSpeeds(SWIGTYPE_p_double spds) {
    bool ret = yarpPINVOKE.IPositionControl_setRefSpeeds__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(spds));
    return ret;
  }

  public virtual bool setRefAcceleration(int j, double acc) {
    bool ret = yarpPINVOKE.IPositionControl_setRefAcceleration(swigCPtr, j, acc);
    return ret;
  }

  public virtual bool setRefAccelerations(SWIGTYPE_p_double accs) {
    bool ret = yarpPINVOKE.IPositionControl_setRefAccelerations__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(accs));
    return ret;
  }

  public virtual bool getRefSpeed(int j, SWIGTYPE_p_double arg1) {
    bool ret = yarpPINVOKE.IPositionControl_getRefSpeed__SWIG_0(swigCPtr, j, SWIGTYPE_p_double.getCPtr(arg1));
    return ret;
  }

  public virtual bool getRefSpeeds(SWIGTYPE_p_double spds) {
    bool ret = yarpPINVOKE.IPositionControl_getRefSpeeds__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(spds));
    return ret;
  }

  public virtual bool getRefAcceleration(int j, SWIGTYPE_p_double acc) {
    bool ret = yarpPINVOKE.IPositionControl_getRefAcceleration__SWIG_0(swigCPtr, j, SWIGTYPE_p_double.getCPtr(acc));
    return ret;
  }

  public virtual bool getRefAccelerations(SWIGTYPE_p_double accs) {
    bool ret = yarpPINVOKE.IPositionControl_getRefAccelerations__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(accs));
    return ret;
  }

  public virtual bool stop(int j) {
    bool ret = yarpPINVOKE.IPositionControl_stop__SWIG_0(swigCPtr, j);
    return ret;
  }

  public virtual bool stop() {
    bool ret = yarpPINVOKE.IPositionControl_stop__SWIG_1(swigCPtr);
    return ret;
  }

  public virtual bool positionMove(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double refs) {
    bool ret = yarpPINVOKE.IPositionControl_positionMove__SWIG_2(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(refs));
    return ret;
  }

  public virtual bool relativeMove(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double deltas) {
    bool ret = yarpPINVOKE.IPositionControl_relativeMove__SWIG_2(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(deltas));
    return ret;
  }

  public virtual bool checkMotionDone(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_bool flags) {
    bool ret = yarpPINVOKE.IPositionControl_checkMotionDone__SWIG_2(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_bool.getCPtr(flags));
    return ret;
  }

  public virtual bool setRefSpeeds(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double spds) {
    bool ret = yarpPINVOKE.IPositionControl_setRefSpeeds__SWIG_1(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(spds));
    return ret;
  }

  public virtual bool setRefAccelerations(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double accs) {
    bool ret = yarpPINVOKE.IPositionControl_setRefAccelerations__SWIG_1(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(accs));
    return ret;
  }

  public virtual bool getRefSpeeds(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double spds) {
    bool ret = yarpPINVOKE.IPositionControl_getRefSpeeds__SWIG_1(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(spds));
    return ret;
  }

  public virtual bool getRefAccelerations(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double accs) {
    bool ret = yarpPINVOKE.IPositionControl_getRefAccelerations__SWIG_1(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(accs));
    return ret;
  }

  public virtual bool stop(int n_joint, SWIGTYPE_p_int joints) {
    bool ret = yarpPINVOKE.IPositionControl_stop__SWIG_2(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints));
    return ret;
  }

  public virtual bool getTargetPosition(int joint, SWIGTYPE_p_double arg1) {
    bool ret = yarpPINVOKE.IPositionControl_getTargetPosition(swigCPtr, joint, SWIGTYPE_p_double.getCPtr(arg1));
    return ret;
  }

  public virtual bool getTargetPositions(SWIGTYPE_p_double refs) {
    bool ret = yarpPINVOKE.IPositionControl_getTargetPositions__SWIG_0(swigCPtr, SWIGTYPE_p_double.getCPtr(refs));
    return ret;
  }

  public virtual bool getTargetPositions(int n_joint, SWIGTYPE_p_int joints, SWIGTYPE_p_double refs) {
    bool ret = yarpPINVOKE.IPositionControl_getTargetPositions__SWIG_1(swigCPtr, n_joint, SWIGTYPE_p_int.getCPtr(joints), SWIGTYPE_p_double.getCPtr(refs));
    return ret;
  }

  public int getAxes() {
    int ret = yarpPINVOKE.IPositionControl_getAxes__SWIG_1(swigCPtr);
    return ret;
  }

  public bool positionMove(DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_positionMove__SWIG_3(swigCPtr, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool relativeMove(DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_relativeMove__SWIG_3(swigCPtr, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool setRefSpeeds(DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_setRefSpeeds__SWIG_2(swigCPtr, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getRefSpeed(int j, DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_getRefSpeed__SWIG_1(swigCPtr, j, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getRefSpeeds(DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_getRefSpeeds__SWIG_2(swigCPtr, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getRefAcceleration(int j, DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_getRefAcceleration__SWIG_1(swigCPtr, j, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool getRefAccelerations(DVector data) {
    bool ret = yarpPINVOKE.IPositionControl_getRefAccelerations__SWIG_2(swigCPtr, DVector.getCPtr(data));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool checkMotionDone() {
    bool ret = yarpPINVOKE.IPositionControl_checkMotionDone__SWIG_3(swigCPtr);
    return ret;
  }

  public bool checkMotionDone(BVector flag) {
    bool ret = yarpPINVOKE.IPositionControl_checkMotionDone__SWIG_4(swigCPtr, BVector.getCPtr(flag));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool checkMotionDone(int i, BVector flag) {
    bool ret = yarpPINVOKE.IPositionControl_checkMotionDone__SWIG_5(swigCPtr, i, BVector.getCPtr(flag));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool isMotionDone(int i) {
    bool ret = yarpPINVOKE.IPositionControl_isMotionDone__SWIG_0(swigCPtr, i);
    return ret;
  }

  public bool isMotionDone() {
    bool ret = yarpPINVOKE.IPositionControl_isMotionDone__SWIG_1(swigCPtr);
    return ret;
  }

}
