//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class IThreeAxisGyroscopes : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal IThreeAxisGyroscopes(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(IThreeAxisGyroscopes obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~IThreeAxisGyroscopes() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_IThreeAxisGyroscopes(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual uint getNrOfThreeAxisGyroscopes() {
    uint ret = yarpPINVOKE.IThreeAxisGyroscopes_getNrOfThreeAxisGyroscopes(swigCPtr);
    return ret;
  }

  public virtual MAS_status getThreeAxisGyroscopeStatus(uint sens_index) {
    MAS_status ret = (MAS_status)yarpPINVOKE.IThreeAxisGyroscopes_getThreeAxisGyroscopeStatus(swigCPtr, sens_index);
    return ret;
  }

  public virtual bool getThreeAxisGyroscopeName(uint sens_index, SWIGTYPE_p_std__string name) {
    bool ret = yarpPINVOKE.IThreeAxisGyroscopes_getThreeAxisGyroscopeName(swigCPtr, sens_index, SWIGTYPE_p_std__string.getCPtr(name));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool getThreeAxisGyroscopeFrameName(uint sens_index, SWIGTYPE_p_std__string frameName) {
    bool ret = yarpPINVOKE.IThreeAxisGyroscopes_getThreeAxisGyroscopeFrameName(swigCPtr, sens_index, SWIGTYPE_p_std__string.getCPtr(frameName));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual bool getThreeAxisGyroscopeMeasure(uint sens_index, Vector arg1, SWIGTYPE_p_double timestamp) {
    bool ret = yarpPINVOKE.IThreeAxisGyroscopes_getThreeAxisGyroscopeMeasure(swigCPtr, sens_index, Vector.getCPtr(arg1), SWIGTYPE_p_double.getCPtr(timestamp));
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}
