//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum MAS_status {
  MAS_OK = 0,
  MAS_ERROR = 1,
  MAS_OVF = 2,
  MAS_TIMEOUT = 3,
  MAS_WAITING_FOR_FIRST_READ = 4,
  MAS_UNKNOWN = 5
}
