//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class PixelBgr : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal PixelBgr(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(PixelBgr obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~PixelBgr() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_PixelBgr(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public byte b {
    set {
      yarpPINVOKE.PixelBgr_b_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelBgr_b_get(swigCPtr);
      return ret;
    } 
  }

  public byte g {
    set {
      yarpPINVOKE.PixelBgr_g_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelBgr_g_get(swigCPtr);
      return ret;
    } 
  }

  public byte r {
    set {
      yarpPINVOKE.PixelBgr_r_set(swigCPtr, value);
    } 
    get {
      byte ret = yarpPINVOKE.PixelBgr_r_get(swigCPtr);
      return ret;
    } 
  }

  public PixelBgr() : this(yarpPINVOKE.new_PixelBgr__SWIG_0(), true) {
  }

  public PixelBgr(byte n_r, byte n_g, byte n_b) : this(yarpPINVOKE.new_PixelBgr__SWIG_1(n_r, n_g, n_b), true) {
  }

}
