//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class SearchReport : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal SearchReport(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(SearchReport obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~SearchReport() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          yarpPINVOKE.delete_SearchReport(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public string key {
    set {
      yarpPINVOKE.SearchReport_key_set(swigCPtr, value);
      if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = yarpPINVOKE.SearchReport_key_get(swigCPtr);
      if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public string value {
    set {
      yarpPINVOKE.SearchReport_value_set(swigCPtr, value);
      if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      string ret = yarpPINVOKE.SearchReport_value_get(swigCPtr);
      if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool isFound {
    set {
      yarpPINVOKE.SearchReport_isFound_set(swigCPtr, value);
    } 
    get {
      bool ret = yarpPINVOKE.SearchReport_isFound_get(swigCPtr);
      return ret;
    } 
  }

  public bool isGroup {
    set {
      yarpPINVOKE.SearchReport_isGroup_set(swigCPtr, value);
    } 
    get {
      bool ret = yarpPINVOKE.SearchReport_isGroup_get(swigCPtr);
      return ret;
    } 
  }

  public bool isComment {
    set {
      yarpPINVOKE.SearchReport_isComment_set(swigCPtr, value);
    } 
    get {
      bool ret = yarpPINVOKE.SearchReport_isComment_get(swigCPtr);
      return ret;
    } 
  }

  public bool isDefault {
    set {
      yarpPINVOKE.SearchReport_isDefault_set(swigCPtr, value);
    } 
    get {
      bool ret = yarpPINVOKE.SearchReport_isDefault_get(swigCPtr);
      return ret;
    } 
  }

  public SearchReport() : this(yarpPINVOKE.new_SearchReport(), true) {
  }

}
