//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class yarp {
  public static int createVocab(char a, char b, char c, char d) {
    int ret = yarpPINVOKE.createVocab__SWIG_0(a, b, c, d);
    return ret;
  }

  public static int createVocab(char a, char b, char c) {
    int ret = yarpPINVOKE.createVocab__SWIG_1(a, b, c);
    return ret;
  }

  public static int createVocab(char a, char b) {
    int ret = yarpPINVOKE.createVocab__SWIG_2(a, b);
    return ret;
  }

  public static int createVocab(char a) {
    int ret = yarpPINVOKE.createVocab__SWIG_3(a);
    return ret;
  }

  public static int encode(string str) {
    int ret = yarpPINVOKE.encode(str);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static string decode(int code) {
    string ret = yarpPINVOKE.decode(code);
    return ret;
  }

  public static int VOCAB(char a, char b, char c, char d) {
    int ret = yarpPINVOKE.VOCAB(a, b, c, d);
    return ret;
  }

  public static int VOCAB4(char a, char b, char c, char d) {
    int ret = yarpPINVOKE.VOCAB4(a, b, c, d);
    return ret;
  }

  public static int VOCAB3(char a, char b, char c) {
    int ret = yarpPINVOKE.VOCAB3(a, b, c);
    return ret;
  }

  public static int VOCAB2(char a, char b) {
    int ret = yarpPINVOKE.VOCAB2(a, b);
    return ret;
  }

  public static int VOCAB1(char a) {
    int ret = yarpPINVOKE.VOCAB1(a);
    return ret;
  }

  public static int BOTTLE_TAG_DOUBLE {
    get {
      int ret = yarpPINVOKE.BOTTLE_TAG_DOUBLE_get();
      return ret;
    } 
  }

  public static int BOTTLE_TAG_INT {
    get {
      int ret = yarpPINVOKE.BOTTLE_TAG_INT_get();
      return ret;
    } 
  }

  public static void delay(double seconds) {
    yarpPINVOKE.delay(seconds);
  }

  public static double now() {
    double ret = yarpPINVOKE.now();
    return ret;
  }

  public static void yield() {
    yarpPINVOKE.yield();
  }

  public static void useSystemClock() {
    yarpPINVOKE.useSystemClock();
  }

  public static void useNetworkClock(string clock, string localPortName) {
    yarpPINVOKE.useNetworkClock__SWIG_0(clock, localPortName);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void useNetworkClock(string clock) {
    yarpPINVOKE.useNetworkClock__SWIG_1(clock);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
  }

  public static void useCustomClock(SWIGTYPE_p_Clock clock) {
    yarpPINVOKE.useCustomClock(SWIGTYPE_p_Clock.getCPtr(clock));
  }

  public static bool isSystemClock() {
    bool ret = yarpPINVOKE.isSystemClock();
    return ret;
  }

  public static bool isNetworkClock() {
    bool ret = yarpPINVOKE.isNetworkClock();
    return ret;
  }

  public static bool isCustomClock() {
    bool ret = yarpPINVOKE.isCustomClock();
    return ret;
  }

  public static yarpClockType getClockType() {
    yarpClockType ret = (yarpClockType)yarpPINVOKE.getClockType();
    return ret;
  }

  public static string clockTypeToString(yarpClockType type) {
    string ret = yarpPINVOKE.clockTypeToString((int)type);
    return ret;
  }

  public static bool isValid() {
    bool ret = yarpPINVOKE.isValid();
    return ret;
  }

  public static void turboBoost() {
    yarpPINVOKE.turboBoost();
  }

  public static void yarp_print_trace(SWIGTYPE_p_FILE arg0, string file, int line) {
    yarpPINVOKE.yarp_print_trace(SWIGTYPE_p_FILE.getCPtr(arg0), file, line);
  }

  public static int PAD_BYTES(uint len, uint pad) {
    int ret = yarpPINVOKE.PAD_BYTES(len, pad);
    return ret;
  }

  public new static bool read(ImageRgb dest, string src, image_fileformat format) {
    bool ret = yarpPINVOKE.read__SWIG_0(ImageRgb.getCPtr(dest), src, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageRgb dest, string src) {
    bool ret = yarpPINVOKE.read__SWIG_1(ImageRgb.getCPtr(dest), src);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t dest, string src, image_fileformat format) {
    bool ret = yarpPINVOKE.read__SWIG_2(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t.getCPtr(dest), src, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t dest, string src) {
    bool ret = yarpPINVOKE.read__SWIG_3(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t.getCPtr(dest), src);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageRgba dest, string src, image_fileformat format) {
    bool ret = yarpPINVOKE.read__SWIG_4(ImageRgba.getCPtr(dest), src, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageRgba dest, string src) {
    bool ret = yarpPINVOKE.read__SWIG_5(ImageRgba.getCPtr(dest), src);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageMono dest, string src, image_fileformat format) {
    bool ret = yarpPINVOKE.read__SWIG_6(ImageMono.getCPtr(dest), src, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageMono dest, string src) {
    bool ret = yarpPINVOKE.read__SWIG_7(ImageMono.getCPtr(dest), src);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageFloat dest, string src, image_fileformat format) {
    bool ret = yarpPINVOKE.read__SWIG_8(ImageFloat.getCPtr(dest), src, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool read(ImageFloat dest, string src) {
    bool ret = yarpPINVOKE.read__SWIG_9(ImageFloat.getCPtr(dest), src);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageRgb src, string dest, image_fileformat format) {
    bool ret = yarpPINVOKE.write__SWIG_0(ImageRgb.getCPtr(src), dest, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageRgb src, string dest) {
    bool ret = yarpPINVOKE.write__SWIG_1(ImageRgb.getCPtr(src), dest);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t src, string dest, image_fileformat format) {
    bool ret = yarpPINVOKE.write__SWIG_2(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t.getCPtr(src), dest, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t src, string dest) {
    bool ret = yarpPINVOKE.write__SWIG_3(SWIGTYPE_p_yarp__sig__ImageOfT_yarp__sig__PixelBgr_t.getCPtr(src), dest);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageRgba src, string dest, image_fileformat format) {
    bool ret = yarpPINVOKE.write__SWIG_4(ImageRgba.getCPtr(src), dest, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageRgba src, string dest) {
    bool ret = yarpPINVOKE.write__SWIG_5(ImageRgba.getCPtr(src), dest);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageMono src, string dest, image_fileformat format) {
    bool ret = yarpPINVOKE.write__SWIG_6(ImageMono.getCPtr(src), dest, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageMono src, string dest) {
    bool ret = yarpPINVOKE.write__SWIG_7(ImageMono.getCPtr(src), dest);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageFloat src, string dest, image_fileformat format) {
    bool ret = yarpPINVOKE.write__SWIG_8(ImageFloat.getCPtr(src), dest, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(ImageFloat src, string dest) {
    bool ret = yarpPINVOKE.write__SWIG_9(ImageFloat.getCPtr(src), dest);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(Image src, string dest, image_fileformat format) {
    bool ret = yarpPINVOKE.write__SWIG_10(Image.getCPtr(src), dest, (int)format);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public new static bool write(Image src, string dest) {
    bool ret = yarpPINVOKE.write__SWIG_11(Image.getCPtr(src), dest);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool submatrix(Matrix arg0, Matrix arg1, uint r1, uint r2, uint c1, uint c2) {
    bool ret = yarpPINVOKE.submatrix(Matrix.getCPtr(arg0), Matrix.getCPtr(arg1), r1, r2, c1, c2);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool removeCols(Matrix arg0, Matrix arg1, uint first_col, uint how_many) {
    bool ret = yarpPINVOKE.removeCols(Matrix.getCPtr(arg0), Matrix.getCPtr(arg1), first_col, how_many);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static bool removeRows(Matrix arg0, Matrix arg1, uint first_row, uint how_many) {
    bool ret = yarpPINVOKE.removeRows(Matrix.getCPtr(arg0), Matrix.getCPtr(arg1), first_row, how_many);
    if (yarpPINVOKE.SWIGPendingException.Pending) throw yarpPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static int VOCAB_FRAMEGRABBER_IMAGE {
    get {
      int ret = yarpPINVOKE.VOCAB_FRAMEGRABBER_IMAGE_get();
      return ret;
    } 
  }

  public static int VOCAB_FRAMEGRABBER_IMAGERAW {
    get {
      int ret = yarpPINVOKE.VOCAB_FRAMEGRABBER_IMAGERAW_get();
      return ret;
    } 
  }

  public static int VOCAB_BRIGHTNESS {
    get {
      int ret = yarpPINVOKE.VOCAB_BRIGHTNESS_get();
      return ret;
    } 
  }

  public static int VOCAB_EXPOSURE {
    get {
      int ret = yarpPINVOKE.VOCAB_EXPOSURE_get();
      return ret;
    } 
  }

  public static int VOCAB_SHARPNESS {
    get {
      int ret = yarpPINVOKE.VOCAB_SHARPNESS_get();
      return ret;
    } 
  }

  public static int VOCAB_WHITE {
    get {
      int ret = yarpPINVOKE.VOCAB_WHITE_get();
      return ret;
    } 
  }

  public static int VOCAB_HUE {
    get {
      int ret = yarpPINVOKE.VOCAB_HUE_get();
      return ret;
    } 
  }

  public static int VOCAB_SATURATION {
    get {
      int ret = yarpPINVOKE.VOCAB_SATURATION_get();
      return ret;
    } 
  }

  public static int VOCAB_GAMMA {
    get {
      int ret = yarpPINVOKE.VOCAB_GAMMA_get();
      return ret;
    } 
  }

  public static int VOCAB_SHUTTER {
    get {
      int ret = yarpPINVOKE.VOCAB_SHUTTER_get();
      return ret;
    } 
  }

  public static int VOCAB_GAIN {
    get {
      int ret = yarpPINVOKE.VOCAB_GAIN_get();
      return ret;
    } 
  }

  public static int VOCAB_IRIS {
    get {
      int ret = yarpPINVOKE.VOCAB_IRIS_get();
      return ret;
    } 
  }

  public static int VOCAB_CROP {
    get {
      int ret = yarpPINVOKE.VOCAB_CROP_get();
      return ret;
    } 
  }

  public static int VOCAB_FRAMEGRABBER_CONTROL {
    get {
      int ret = yarpPINVOKE.VOCAB_FRAMEGRABBER_CONTROL_get();
      return ret;
    } 
  }

  public static int VOCAB_FRAMEGRABBER_CONTROL_DC1394 {
    get {
      int ret = yarpPINVOKE.VOCAB_FRAMEGRABBER_CONTROL_DC1394_get();
      return ret;
    } 
  }

  public static int VOCAB_CAMERA_DESCRIPTION {
    get {
      int ret = yarpPINVOKE.VOCAB_CAMERA_DESCRIPTION_get();
      return ret;
    } 
  }

  public static int VOCAB_HAS {
    get {
      int ret = yarpPINVOKE.VOCAB_HAS_get();
      return ret;
    } 
  }

  public static int VOCAB_FEATURE {
    get {
      int ret = yarpPINVOKE.VOCAB_FEATURE_get();
      return ret;
    } 
  }

  public static int VOCAB_FEATURE2 {
    get {
      int ret = yarpPINVOKE.VOCAB_FEATURE2_get();
      return ret;
    } 
  }

  public static int VOCAB_ONOFF {
    get {
      int ret = yarpPINVOKE.VOCAB_ONOFF_get();
      return ret;
    } 
  }

  public static int VOCAB_AUTO {
    get {
      int ret = yarpPINVOKE.VOCAB_AUTO_get();
      return ret;
    } 
  }

  public static int VOCAB_MANUAL {
    get {
      int ret = yarpPINVOKE.VOCAB_MANUAL_get();
      return ret;
    } 
  }

  public static int VOCAB_ONEPUSH {
    get {
      int ret = yarpPINVOKE.VOCAB_ONEPUSH_get();
      return ret;
    } 
  }

  public static int VOCAB_ACTIVE {
    get {
      int ret = yarpPINVOKE.VOCAB_ACTIVE_get();
      return ret;
    } 
  }

  public static int VOCAB_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_DRHASFEA {
    get {
      int ret = yarpPINVOKE.VOCAB_DRHASFEA_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETVAL {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETVAL_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETVAL {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETVAL_get();
      return ret;
    } 
  }

  public static int VOCAB_DRHASACT {
    get {
      int ret = yarpPINVOKE.VOCAB_DRHASACT_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETACT {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETACT_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETACT {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETACT_get();
      return ret;
    } 
  }

  public static int VOCAB_DRHASMAN {
    get {
      int ret = yarpPINVOKE.VOCAB_DRHASMAN_get();
      return ret;
    } 
  }

  public static int VOCAB_DRHASAUT {
    get {
      int ret = yarpPINVOKE.VOCAB_DRHASAUT_get();
      return ret;
    } 
  }

  public static int VOCAB_DRHASONP {
    get {
      int ret = yarpPINVOKE.VOCAB_DRHASONP_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETMOD {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETMOD_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETMOD {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETMOD_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETONP {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETONP_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETMSK {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETMSK_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETVMD {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETVMD_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETVMD {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETVMD_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETFPM {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETFPM_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETFPS {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETFPS_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETFPS {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETFPS_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETISO {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETISO_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETISO {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETISO_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETCCM {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETCCM_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETCOD {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETCOD_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETCOD {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETCOD_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETWHB {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETWHB_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETWHB {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETWHB_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETF7M {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETF7M_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETWF7 {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETWF7_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETWF7 {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETWF7_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETOPM {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETOPM_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETOPM {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETOPM_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETTXM {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETTXM_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETTXM {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETTXM_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETBCS {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETBCS_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETDEF {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETDEF_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETRST {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETRST_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETPWR {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETPWR_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETCAP {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETCAP_get();
      return ret;
    } 
  }

  public static int VOCAB_DRSETBPP {
    get {
      int ret = yarpPINVOKE.VOCAB_DRSETBPP_get();
      return ret;
    } 
  }

  public static int VOCAB_DRGETBPP {
    get {
      int ret = yarpPINVOKE.VOCAB_DRGETBPP_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTION_DONE {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTION_DONE_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTION_DONES {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTION_DONES_get();
      return ret;
    } 
  }

  public static int VOCAB_TIMESTAMP {
    get {
      int ret = yarpPINVOKE.VOCAB_TIMESTAMP_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_MOVE {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_MOVE_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_MOVES {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_MOVES_get();
      return ret;
    } 
  }

  public static int VOCAB_RELATIVE_MOVE {
    get {
      int ret = yarpPINVOKE.VOCAB_RELATIVE_MOVE_get();
      return ret;
    } 
  }

  public static int VOCAB_RELATIVE_MOVES {
    get {
      int ret = yarpPINVOKE.VOCAB_RELATIVE_MOVES_get();
      return ret;
    } 
  }

  public static int VOCAB_REF_SPEED {
    get {
      int ret = yarpPINVOKE.VOCAB_REF_SPEED_get();
      return ret;
    } 
  }

  public static int VOCAB_REF_SPEEDS {
    get {
      int ret = yarpPINVOKE.VOCAB_REF_SPEEDS_get();
      return ret;
    } 
  }

  public static int VOCAB_REF_ACCELERATION {
    get {
      int ret = yarpPINVOKE.VOCAB_REF_ACCELERATION_get();
      return ret;
    } 
  }

  public static int VOCAB_REF_ACCELERATIONS {
    get {
      int ret = yarpPINVOKE.VOCAB_REF_ACCELERATIONS_get();
      return ret;
    } 
  }

  public static int VOCAB_STOP {
    get {
      int ret = yarpPINVOKE.VOCAB_STOP_get();
      return ret;
    } 
  }

  public static int VOCAB_STOPS {
    get {
      int ret = yarpPINVOKE.VOCAB_STOPS_get();
      return ret;
    } 
  }

  public static int VOCAB_VELOCITY_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_VELOCITY_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_VELOCITY_MOVE {
    get {
      int ret = yarpPINVOKE.VOCAB_VELOCITY_MOVE_get();
      return ret;
    } 
  }

  public static int VOCAB_VELOCITY_MOVES {
    get {
      int ret = yarpPINVOKE.VOCAB_VELOCITY_MOVES_get();
      return ret;
    } 
  }

  public static int VOCAB_PROTOCOL_VERSION {
    get {
      int ret = yarpPINVOKE.VOCAB_PROTOCOL_VERSION_get();
      return ret;
    } 
  }

  public static int VOCAB_INFO_NAME {
    get {
      int ret = yarpPINVOKE.VOCAB_INFO_NAME_get();
      return ret;
    } 
  }

  public static int VOCAB_INFO_TYPE {
    get {
      int ret = yarpPINVOKE.VOCAB_INFO_TYPE_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_ENABLE {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_ENABLE_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_DISABLE {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_DISABLE_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_STATUS {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_STATUS_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_STATUS_SINGLE {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_STATUS_SINGLE_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_CURRENT {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_CURRENT_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_CURRENTS {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_CURRENTS_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_MAXCURRENT {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_MAXCURRENT_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_NOMINAL_CURRENT {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_NOMINAL_CURRENT_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_PEAK_CURRENT {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_PEAK_CURRENT_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_PWM {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_PWM_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_PWM_LIMIT {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_PWM_LIMIT_get();
      return ret;
    } 
  }

  public static int VOCAB_AMP_VOLTAGE_SUPPLY {
    get {
      int ret = yarpPINVOKE.VOCAB_AMP_VOLTAGE_SUPPLY_get();
      return ret;
    } 
  }

  public static int VOCAB_LIMITS {
    get {
      int ret = yarpPINVOKE.VOCAB_LIMITS_get();
      return ret;
    } 
  }

  public static int VOCAB_VEL_LIMITS {
    get {
      int ret = yarpPINVOKE.VOCAB_VEL_LIMITS_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_MOVE_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_MOVE_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_RELATIVE_MOVE_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_RELATIVE_MOVE_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTION_DONE_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTION_DONE_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_REF_SPEED_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_REF_SPEED_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_REF_ACCELERATION_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_REF_ACCELERATION_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_STOP_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_STOP_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_E_RESET {
    get {
      int ret = yarpPINVOKE.VOCAB_E_RESET_get();
      return ret;
    } 
  }

  public static int VOCAB_E_RESETS {
    get {
      int ret = yarpPINVOKE.VOCAB_E_RESETS_get();
      return ret;
    } 
  }

  public static int VOCAB_ENCODER {
    get {
      int ret = yarpPINVOKE.VOCAB_ENCODER_get();
      return ret;
    } 
  }

  public static int VOCAB_ENCODERS {
    get {
      int ret = yarpPINVOKE.VOCAB_ENCODERS_get();
      return ret;
    } 
  }

  public static int VOCAB_ENCODER_SPEED {
    get {
      int ret = yarpPINVOKE.VOCAB_ENCODER_SPEED_get();
      return ret;
    } 
  }

  public static int VOCAB_ENCODER_SPEEDS {
    get {
      int ret = yarpPINVOKE.VOCAB_ENCODER_SPEEDS_get();
      return ret;
    } 
  }

  public static int VOCAB_ENCODER_ACCELERATION {
    get {
      int ret = yarpPINVOKE.VOCAB_ENCODER_ACCELERATION_get();
      return ret;
    } 
  }

  public static int VOCAB_ENCODER_ACCELERATIONS {
    get {
      int ret = yarpPINVOKE.VOCAB_ENCODER_ACCELERATIONS_get();
      return ret;
    } 
  }

  public static int VOCAB_REMOTE_CALIBRATOR_INTERFACE {
    get {
      int ret = yarpPINVOKE.VOCAB_REMOTE_CALIBRATOR_INTERFACE_get();
      return ret;
    } 
  }

  public static int VOCAB_IS_CALIBRATOR_PRESENT {
    get {
      int ret = yarpPINVOKE.VOCAB_IS_CALIBRATOR_PRESENT_get();
      return ret;
    } 
  }

  public static int VOCAB_CALIBRATE_SINGLE_JOINT {
    get {
      int ret = yarpPINVOKE.VOCAB_CALIBRATE_SINGLE_JOINT_get();
      return ret;
    } 
  }

  public static int VOCAB_CALIBRATE_WHOLE_PART {
    get {
      int ret = yarpPINVOKE.VOCAB_CALIBRATE_WHOLE_PART_get();
      return ret;
    } 
  }

  public static int VOCAB_HOMING_SINGLE_JOINT {
    get {
      int ret = yarpPINVOKE.VOCAB_HOMING_SINGLE_JOINT_get();
      return ret;
    } 
  }

  public static int VOCAB_HOMING_WHOLE_PART {
    get {
      int ret = yarpPINVOKE.VOCAB_HOMING_WHOLE_PART_get();
      return ret;
    } 
  }

  public static int VOCAB_PARK_SINGLE_JOINT {
    get {
      int ret = yarpPINVOKE.VOCAB_PARK_SINGLE_JOINT_get();
      return ret;
    } 
  }

  public static int VOCAB_PARK_WHOLE_PART {
    get {
      int ret = yarpPINVOKE.VOCAB_PARK_WHOLE_PART_get();
      return ret;
    } 
  }

  public static int VOCAB_QUIT_CALIBRATE {
    get {
      int ret = yarpPINVOKE.VOCAB_QUIT_CALIBRATE_get();
      return ret;
    } 
  }

  public static int VOCAB_QUIT_PARK {
    get {
      int ret = yarpPINVOKE.VOCAB_QUIT_PARK_get();
      return ret;
    } 
  }

  public static int VOCAB_ICONTROLMODE {
    get {
      int ret = yarpPINVOKE.VOCAB_ICONTROLMODE_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CONTROL_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CONTROL_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CONTROL_MODE_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CONTROL_MODE_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CONTROL_MODES {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CONTROL_MODES_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_IDLE {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_IDLE_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_TORQUE {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_TORQUE_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_POSITION {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_POSITION_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_POSITION_DIRECT {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_POSITION_DIRECT_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_VELOCITY {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_VELOCITY_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CURRENT {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CURRENT_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_PWM {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_PWM_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_IMPEDANCE_POS {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_IMPEDANCE_POS_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_IMPEDANCE_VEL {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_IMPEDANCE_VEL_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_MIXED {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_MIXED_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_FORCE_IDLE {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_FORCE_IDLE_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_HW_FAULT {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_HW_FAULT_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CALIBRATING {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CALIBRATING_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CALIB_DONE {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CALIB_DONE_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_NOT_CONFIGURED {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_NOT_CONFIGURED_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_CONFIGURED {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_CONFIGURED_get();
      return ret;
    } 
  }

  public static int VOCAB_CM_UNKNOWN {
    get {
      int ret = yarpPINVOKE.VOCAB_CM_UNKNOWN_get();
      return ret;
    } 
  }

  public static int VOCAB_INTERFACE_INTERACTION_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_INTERFACE_INTERACTION_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_INTERACTION_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_INTERACTION_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_INTERACTION_MODE_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_INTERACTION_MODE_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_INTERACTION_MODES {
    get {
      int ret = yarpPINVOKE.VOCAB_INTERACTION_MODES_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_E_RESET {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_E_RESET_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_E_RESETS {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_E_RESETS_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODER {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODER_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODERS {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODERS_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_CPR {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_CPR_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODER_NUMBER {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODER_NUMBER_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODER_SPEED {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODER_SPEED_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODER_SPEEDS {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODER_SPEEDS_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODER_ACCELERATION {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODER_ACCELERATION_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_ENCODER_ACCELERATIONS {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_ENCODER_ACCELERATIONS_get();
      return ret;
    } 
  }

  public static int VOCAB_TORQUE {
    get {
      int ret = yarpPINVOKE.VOCAB_TORQUE_get();
      return ret;
    } 
  }

  public static int VOCAB_TORQUE_MODE {
    get {
      int ret = yarpPINVOKE.VOCAB_TORQUE_MODE_get();
      return ret;
    } 
  }

  public static int VOCAB_TRQS {
    get {
      int ret = yarpPINVOKE.VOCAB_TRQS_get();
      return ret;
    } 
  }

  public static int VOCAB_TRQ {
    get {
      int ret = yarpPINVOKE.VOCAB_TRQ_get();
      return ret;
    } 
  }

  public static int VOCAB_BEMF {
    get {
      int ret = yarpPINVOKE.VOCAB_BEMF_get();
      return ret;
    } 
  }

  public static int VOCAB_MOTOR_PARAMS {
    get {
      int ret = yarpPINVOKE.VOCAB_MOTOR_PARAMS_get();
      return ret;
    } 
  }

  public static int VOCAB_RANGES {
    get {
      int ret = yarpPINVOKE.VOCAB_RANGES_get();
      return ret;
    } 
  }

  public static int VOCAB_RANGE {
    get {
      int ret = yarpPINVOKE.VOCAB_RANGE_get();
      return ret;
    } 
  }

  public static int VOCAB_IMP_PARAM {
    get {
      int ret = yarpPINVOKE.VOCAB_IMP_PARAM_get();
      return ret;
    } 
  }

  public static int VOCAB_IMP_OFFSET {
    get {
      int ret = yarpPINVOKE.VOCAB_IMP_OFFSET_get();
      return ret;
    } 
  }

  public static int VOCAB_TORQUES_DIRECTS {
    get {
      int ret = yarpPINVOKE.VOCAB_TORQUES_DIRECTS_get();
      return ret;
    } 
  }

  public static int VOCAB_TORQUES_DIRECT {
    get {
      int ret = yarpPINVOKE.VOCAB_TORQUES_DIRECT_get();
      return ret;
    } 
  }

  public static int VOCAB_TORQUES_DIRECT_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_TORQUES_DIRECT_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_IMPEDANCE {
    get {
      int ret = yarpPINVOKE.VOCAB_IMPEDANCE_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_get();
      return ret;
    } 
  }

  public static int VOCAB_VELOCITY {
    get {
      int ret = yarpPINVOKE.VOCAB_VELOCITY_get();
      return ret;
    } 
  }

  public static int VOCAB_VELOCITY_MOVE_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_VELOCITY_MOVE_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_VEL_PID {
    get {
      int ret = yarpPINVOKE.VOCAB_VEL_PID_get();
      return ret;
    } 
  }

  public static int VOCAB_VEL_PIDS {
    get {
      int ret = yarpPINVOKE.VOCAB_VEL_PIDS_get();
      return ret;
    } 
  }

  public static int VOCAB_PWMCONTROL_INTERFACE {
    get {
      int ret = yarpPINVOKE.VOCAB_PWMCONTROL_INTERFACE_get();
      return ret;
    } 
  }

  public static int VOCAB_PWMCONTROL_REF_PWM {
    get {
      int ret = yarpPINVOKE.VOCAB_PWMCONTROL_REF_PWM_get();
      return ret;
    } 
  }

  public static int VOCAB_PWMCONTROL_REF_PWMS {
    get {
      int ret = yarpPINVOKE.VOCAB_PWMCONTROL_REF_PWMS_get();
      return ret;
    } 
  }

  public static int VOCAB_PWMCONTROL_PWM_OUTPUT {
    get {
      int ret = yarpPINVOKE.VOCAB_PWMCONTROL_PWM_OUTPUT_get();
      return ret;
    } 
  }

  public static int VOCAB_PWMCONTROL_PWM_OUTPUTS {
    get {
      int ret = yarpPINVOKE.VOCAB_PWMCONTROL_PWM_OUTPUTS_get();
      return ret;
    } 
  }

  public static int VOCAB_CURRENTCONTROL_INTERFACE {
    get {
      int ret = yarpPINVOKE.VOCAB_CURRENTCONTROL_INTERFACE_get();
      return ret;
    } 
  }

  public static int VOCAB_CURRENT_REF {
    get {
      int ret = yarpPINVOKE.VOCAB_CURRENT_REF_get();
      return ret;
    } 
  }

  public static int VOCAB_CURRENT_REFS {
    get {
      int ret = yarpPINVOKE.VOCAB_CURRENT_REFS_get();
      return ret;
    } 
  }

  public static int VOCAB_CURRENT_REF_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_CURRENT_REF_GROUP_get();
      return ret;
    } 
  }

  public static int VOCAB_CURRENT_RANGE {
    get {
      int ret = yarpPINVOKE.VOCAB_CURRENT_RANGE_get();
      return ret;
    } 
  }

  public static int VOCAB_CURRENT_RANGES {
    get {
      int ret = yarpPINVOKE.VOCAB_CURRENT_RANGES_get();
      return ret;
    } 
  }

  public static int VOCAB_IANALOG {
    get {
      int ret = yarpPINVOKE.VOCAB_IANALOG_get();
      return ret;
    } 
  }

  public static int VOCAB_REMOTE_VARIABILE_INTERFACE {
    get {
      int ret = yarpPINVOKE.VOCAB_REMOTE_VARIABILE_INTERFACE_get();
      return ret;
    } 
  }

  public static int VOCAB_VARIABLE {
    get {
      int ret = yarpPINVOKE.VOCAB_VARIABLE_get();
      return ret;
    } 
  }

  public static int VOCAB_LIST_VARIABLES {
    get {
      int ret = yarpPINVOKE.VOCAB_LIST_VARIABLES_get();
      return ret;
    } 
  }

  public static int VOCAB_PID {
    get {
      int ret = yarpPINVOKE.VOCAB_PID_get();
      return ret;
    } 
  }

  public static int VOCAB_PIDS {
    get {
      int ret = yarpPINVOKE.VOCAB_PIDS_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_DIRECT {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_DIRECT_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_DIRECTS {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_DIRECTS_get();
      return ret;
    } 
  }

  public static int VOCAB_POSITION_DIRECT_GROUP {
    get {
      int ret = yarpPINVOKE.VOCAB_POSITION_DIRECT_GROUP_get();
      return ret;
    } 
  }

  public static readonly int YARP_VERSION_MAJOR = yarpPINVOKE.YARP_VERSION_MAJOR_get();
  public static readonly int YARP_VERSION_MINOR = yarpPINVOKE.YARP_VERSION_MINOR_get();
  public static readonly int YARP_VERSION_PATCH = yarpPINVOKE.YARP_VERSION_PATCH_get();
  public static readonly string YARP_VERSION = yarpPINVOKE.YARP_VERSION_get();
  public static readonly string YARP_VERSION_SHORT = yarpPINVOKE.YARP_VERSION_SHORT_get();
  public static readonly int BOTTLE_TAG_INT8 = yarpPINVOKE.BOTTLE_TAG_INT8_get();
  public static readonly int BOTTLE_TAG_INT16 = yarpPINVOKE.BOTTLE_TAG_INT16_get();
  public static readonly int BOTTLE_TAG_INT32 = yarpPINVOKE.BOTTLE_TAG_INT32_get();
  public static readonly int BOTTLE_TAG_INT64 = yarpPINVOKE.BOTTLE_TAG_INT64_get();
  public static readonly int BOTTLE_TAG_VOCAB = yarpPINVOKE.BOTTLE_TAG_VOCAB_get();
  public static readonly int BOTTLE_TAG_FLOAT32 = yarpPINVOKE.BOTTLE_TAG_FLOAT32_get();
  public static readonly int BOTTLE_TAG_FLOAT64 = yarpPINVOKE.BOTTLE_TAG_FLOAT64_get();
  public static readonly int BOTTLE_TAG_STRING = yarpPINVOKE.BOTTLE_TAG_STRING_get();
  public static readonly int BOTTLE_TAG_BLOB = yarpPINVOKE.BOTTLE_TAG_BLOB_get();
  public static readonly int BOTTLE_TAG_LIST = yarpPINVOKE.BOTTLE_TAG_LIST_get();
  public static readonly int BOTTLE_TAG_DICT = yarpPINVOKE.BOTTLE_TAG_DICT_get();
}
