from constants import PRE,PAR_PRE,CHILD_PRE,REL_PRE,R_ID,KW,CON,VALUE,DRS,VARS,PREDS,SIBL_PRE

def retrieve_professors_names():
    list = []
    #TODO:read RDF CRAWLING tuples and retrieve all professor (surnames/ full names?)
    return list

transform_rules =   [
                        {PRE:{
                            R_ID:KW,
                            VALUE:["lezione","corso"]
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["lecture($1)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["prof","prof.","professore","professor","professoressa"]
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["person($1)","professor($1)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:retrieve_professors_names()
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["person($1)","professor($1)","equals($1,$this.VALUE)"] #TODO: decide both on equals(x,y) [logic variables binding] and constant extraction $this.VALUE
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["un","una","uno","un'"]
                            },
                        DRS:{VARS:[],
                            PREDS:[]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["il","lo","la","i","gli","le"]
                            },
                        DRS:{VARS:[],
                            PREDS:[]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["di","del","dello","della","dei","degli","delle","ha"]
                            },
                        DRS:{VARS:["$1","$2"],
                            PREDS:["own($1,$2)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["quale"]
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["unknown($1)","target($1)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["dove"]
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["location($1)","unknown($1)","target($1)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["chi"]
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["person($1)","unknown($1)","target($1)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["quando","ora"]
                            },
                        DRS:{VARS:["$1"],
                            PREDS:["time($1)","unknown($1)","target($1)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["studio"]
                            },
                        DRS:{
                            VARS:["$l"],
                            PREDS:["location($l)","unknown($l)"]
                            }
                        },
                        {PRE:{
                            R_ID:KW,
                            VALUE:["riceve","ricevimento"]
                            },
                        DRS:{
                            VARS:["$o"],
                            PREDS:["ricevimento($o)","unkwnown($o)"]
                            }
                        }
                    ]
merge_rules =       [
                        {PAR_PRE:{
                            R_ID:CON,
                            VALUE:["professor($1)"]
                            },
                        CHILD_PRE:{
                            R_ID:CON,
                            VALUE:["person($2)"]
                            },
                        REL_PRE:{},
                        PREDS:["equals($1,$2)"]
                        },
                        {PAR_PRE:{
                            R_ID:CON,
                            VALUE:["lecture($1)"]
                            },
                        CHILD_PRE:{
                            R_ID:CON,
                            VALUE:["own($2,$3)"]
                            },
                        REL_PRE:{},
                        PREDS:["equals($1,$3)"]
                        },
                        {PAR_PRE:{
                            R_ID:CON,
                            VALUE:["person($1)"]
                            },
                        CHILD_PRE:{
                            R_ID:CON,
                            VALUE:["own($2,$3)"]
                            },
                        REL_PRE:{},
                        PREDS:["equals($1,$2)"]
                        },
                        {PAR_PRE:{
                            R_ID:CON,
                            VALUE:["location($1)"]
                            },
                        CHILD_PRE:{
                            R_ID:CON,
                            VALUE:["person($2)"]
                            },
                        REL_PRE:{},
                        PREDS:["own($2,$1)"]
                        },
                        {SIBL_PRE:{
                            R_ID:CON,
                            VALUE:["person($1)"]
                            },
                        SIBL_PRE:{
                            R_ID:CON,
                            VALUE:["dipartimento($2)"]
                            },
                        SIBL_PRE:{
                            R_ID:CON,
                            VALUE:["ricevimento($3)"]
                                },
                        SIBL_PRE:{
                            R_ID:CON,
                            VALUE:["unknown($4),location($4)"]
                                },
                        REL_PRE:{},
                        PREDS:["equals($4,$2)"]
                        },
                        {PAR_PRE:{

                        }}
                    ]
rules = {'local' : transform_rules, 'merge' : merge_rules}
